JsonSerializationException caused by slightly different system assembly names when client and server are running on different platforms (full.net, netcore, mono).
> JsonSerializationException: Error resolving type specified in JSON 'System.Object[], System.Private.CoreLib'. Path 'MappedResults[0].Properties[1].Value.Properties[0].Value.Properties[0].Value.$type'
> JsonSerializationException: Could not load assembly 'System.Private.CoreLib'.

TRICK: simply don't export assembly name for system types!

TODO: consider making a separate NuGet package for InfoCarrierJsonSerializerSettingsExtensions?